# Generated by Django 3.2.18 on 2023-03-20 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(default='Challenge', max_length=160)),
                ('description', models.TextField(default='...', max_length=500)),
                ('category', models.CharField(choices=[('Spiritual', 'Spiritual'), ('Financial', 'Financial'), ('Career', 'Career'), ('Intellectual', 'Intellectual'), ('Fitness', 'Fitness'), ('Social', 'Social'), ('Other', 'Other')], default='ETC', max_length=25)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
