# Generated by Django 3.2.18 on 2023-05-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_challenge_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('Positivity Spread', 'Positivity Spread'), ('Fitness', 'Fitness'), ('Adventure', 'Adventure'), ('Creativity', 'Creativity'), ('Social', 'Social'), ('Meme', 'Meme')], default='ETC', max_length=25),
        ),
    ]
