# Generated by Django 3.2.18 on 2023-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challenge_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('Spread Positivity', 'Spread Positivity'), ('Fitness', 'Fitness'), ('Adventure', 'Adventure'), ('Creativity', 'Creativity'), ('Social', 'Social'), ('Meme', 'Meme')], default='ETC', max_length=25),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
