# Generated by Django 3.2.18 on 2023-04-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
