# Generated by Django 3.2.18 on 2023-05-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_upload_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['created_at']},
        ),
    ]
